# Generated by Django 4.1.3 on 2022-11-28 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayat_soalan', models.CharField(max_length=200)),
                ('tarikh_soalan', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Pilihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayat_pilihan', models.CharField(max_length=200)),
                ('undian', models.IntegerField(default=0)),
                ('soalan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimpleApp.soalan')),
            ],
        ),
    ]
